{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_stats AS (
    SELECT * 
    FROM {{ source('nba_project', 'other_stats') }}
    )

SELECT 
	GAME_ID ,
	LEAGUE_ID ,
	TEAM_ID_HOME ,
	CAST(TEAM_ABBREVIATION_HOME AS VARCHAR(255)) AS TEAM_ABBREVIATION_HOME,
	CAST(TEAM_CITY_HOME AS VARCHAR(255)) AS TEAM_CITY_HOME,
	PTS_PAINT_HOME ,
	PTS_2ND_CHANCE_HOME ,
	PTS_FB_HOME ,
	LARGEST_LEAD_HOME ,
	LEAD_CHANGES ,
	TIMES_TIED ,
	TEAM_TURNOVERS_HOME ,
	TOTAL_TURNOVERS_HOME ,
	TEAM_REBOUNDS_HOME ,
	PTS_OFF_TO_HOME ,
	TEAM_ID_AWAY ,
	CAST(TEAM_ABBREVIATION_AWAY AS VARCHAR(255)) AS TEAM_ABBREVIATION_AWAY,
	CAST(TEAM_CITY_AWAY AS VARCHAR(255)) AS TEAM_CITY_AWAY,
	PTS_PAINT_AWAY ,
	PTS_2ND_CHANCE_AWAY ,
	PTS_FB_AWAY ,
	LARGEST_LEAD_AWAY ,
	TEAM_TURNOVERS_AWAY ,
	TOTAL_TURNOVERS_AWAY ,
	TEAM_REBOUNDS_AWAY ,
	PTS_OFF_TO_AWAY 
FROM 
    src_stats