{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_details AS (
    SELECT * 
    FROM {{ source('nba_project', 'team_details') }}
    )

SELECT 
	TEAM_ID,
    CAST(ABBREVIATION AS VARCHAR(255)) AS ABBREVIATION,
    CAST(NICKNAME AS VARCHAR(255)) AS NICKNAME,
    CAST(YEARFOUNDED AS FLOAT) AS YEARFOUNDED,
    CAST(CITY AS VARCHAR(255)) AS CITY,
    CAST(ARENA AS VARCHAR(255)) AS ARENA,
    CAST(ARENACAPACITY AS FLOAT) AS ARENACAPACITY,
    CAST(OWNER AS VARCHAR(255)) AS OWNER,
    CAST(GENERALMANAGER AS VARCHAR(255)) AS GENERALMANAGER,
    CAST(HEADCOACH AS VARCHAR(255)) AS HEADCOACH,
    CAST(DLEAGUEAFFILIATION AS VARCHAR(255)) AS DLEAGUEAFFILIATION,
    
    CAST(FACEBOOK AS VARCHAR(255)) AS FACEBOOK,
    CAST(INSTAGRAM AS VARCHAR(255)) AS INSTAGRAM,
    CAST(TWITTER AS VARCHAR(255)) AS TWITTER
FROM 
    src_details