{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_draft AS (
    SELECT * 
    FROM {{ source('nba_project', 'draft_history') }}
    ),

renamed_casted AS (
    SELECT 
    PERSON_ID AS PLAYER_ID,
    CAST(PLAYER_NAME AS VARCHAR(255)) AS PLAYER_NAME,
    SEASON AS DRAFT_SEASON,
    ROUND_NUMBER AS DRAFT_ROUND_NUMBER,
    ROUND_PICK AS DRAFT_ROUND_PICK,
    OVERALL_PICK AS DRAFT_OVERALL_PICK,
    CAST(DRAFT_TYPE AS VARCHAR(255)) AS DRAFT_TYPE,
    TEAM_ID AS DRAFT_TEAM_ID,
    CAST(TEAM_CITY AS VARCHAR(255)) AS DRAFT_TEAM_CITY,
    CAST(TEAM_NAME AS VARCHAR(255)) AS DRAFT_TEAM_NAME,
    CAST(TEAM_ABBREVIATION AS VARCHAR(255)) AS DRAFT_TEAM_ABBREVIATION,
    ORGANIZATION AS DRAFT_ORGANIZATION,
    ORGANIZATION_TYPE AS DRAFT_ORGANIZATION_TYPE,
    CAST(PLAYER_PROFILE_FLAG AS BOOLEAN) AS DRAFT_PLAYER_PROFILE_FLAG 

    FROM src_draft
    )

SELECT * FROM renamed_casted