{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_games AS (
    SELECT * 
    FROM {{ source('nba_project', 'game') }}
    ),


deduplicated_games AS (
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY GAME_ID ORDER BY GAME_DATE DESC) AS row_num
    FROM 
        src_games
)
SELECT 
    GAME_ID,
    SEASON_ID,
    SEASON_TYPE,
    GAME_DATE,

    TEAM_ID_HOME,
    CAST(TEAM_ABBREVIATION_HOME AS VARCHAR(255)) AS EQUIPO_ABREV_LOC,
    CAST(TEAM_NAME_HOME AS VARCHAR(255)) AS EQUIPO_NOM_LOC,
    CAST(MATCHUP_HOME AS VARCHAR(255)) AS ENFRENT_LOC,
    CAST(WL_HOME AS VARCHAR(255)) AS RESULT_LOC,
    MIN AS MINUTOS_LOC,
    COALESCE(FGM_HOME, 0) AS TC_ENC_LOC,
    COALESCE(FGA_HOME, 0) AS TC_INT_LOC,
    COALESCE(FG_PCT_HOME, 0) AS TC_PCT_LOC,
    COALESCE(FG3M_HOME, 0) AS T3_ENC_LOC,
    COALESCE(FG3A_HOME, 0) AS T3_INT_LOC,
    CAST(FG3_PCT_HOME AS VARCHAR(255)) AS T3_PCT_PORC_LOC,
    COALESCE(FTM_HOME, 0) AS TL_ENC_LOC,
    COALESCE(FTA_HOME, 0) AS TL_INT_LOC,
    COALESCE(FT_PCT_HOME, 0) AS TL_PCT_LOC,
    CAST(OREB_HOME AS VARCHAR(255)) AS REB_OF_LOC,
    CAST(DREB_HOME AS VARCHAR(255)) AS REB_DEF_LOC,
    COALESCE(REB_HOME, 0) AS REB_TOT_LOC,
    COALESCE(AST_HOME, 0) AS ASIST_LOC,
    CAST(STL_HOME AS VARCHAR(255)) AS ROBOS_LOC,
    CAST(BLK_HOME AS VARCHAR(255)) AS TAPONES_LOC,
    CAST(TOV_HOME AS VARCHAR(255)) AS PERDIDAS_LOC,
    COALESCE(PF_HOME, 0) AS FALTAS_LOC,
    COALESCE(PTS_HOME, 0) AS PTS_LOC,
    COALESCE(PLUS_MINUS_HOME, 0) AS PM_LOC,
    CAST(VIDEO_AVAILABLE_HOME AS BOOLEAN) AS VIDEO_AVAILABLE_HOME,

    TEAM_ID_AWAY,
    CAST(TEAM_ABBREVIATION_AWAY AS VARCHAR(255)) AS EQUIPO_ABREV_VIS,
    CAST(TEAM_NAME_AWAY AS VARCHAR(255)) AS EQUIPO_NOM_VIS,
    CAST(MATCHUP_AWAY AS VARCHAR(255)) AS ENFRENT_VIS,
    CAST(WL_AWAY AS VARCHAR(255)) AS RESULT_VIS,
    COALESCE(FGM_AWAY, 0) AS TC_ENC_VIS,
    COALESCE(FGA_AWAY, 0) AS TC_INT_VIS,
    COALESCE(FG_PCT_AWAY, 0) AS TC_PCT_VIS,
    COALESCE(FG3M_AWAY, 0) AS T3_ENC_VIS,
    COALESCE(FG3A_AWAY, 0) AS T3_INT_VIS,
    CAST(FG3_PCT_AWAY AS VARCHAR(255)) AS T3_PCT_PORC_VIS,
    COALESCE(FTM_AWAY, 0) AS TL_ENC_VIS,
    COALESCE(FTA_AWAY, 0) AS TL_INT_VIS,
    COALESCE(FT_PCT_AWAY, 0) AS TL_PCT_VIS,
    CAST(OREB_AWAY AS VARCHAR(255)) AS REB_OF_VIS,
    CAST(DREB_AWAY AS VARCHAR(255)) AS REB_DEF_VIS,
    COALESCE(REB_AWAY, 0) AS REB_TOT_VIS,
    COALESCE(AST_AWAY, 0) AS ASIST_VIS,
    CAST(STL_AWAY AS VARCHAR(255)) AS ROBOS_VIS,
    CAST(BLK_AWAY AS VARCHAR(255)) AS TAPONES_VIS,
    CAST(TOV_AWAY AS VARCHAR(255)) AS PERDIDAS_VIS,
    COALESCE(PF_AWAY, 0) AS FALTAS_VIS,
    COALESCE(PTS_AWAY, 0) AS PTS_VIS,
    COALESCE(PLUS_MINUS_AWAY, 0) AS PM_VIS,
    CAST(VIDEO_AVAILABLE_AWAY AS BOOLEAN) AS VIDEO_AVAILABLE_AWAY
FROM 
    deduplicated_games
WHERE row_num = 1
