{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_scores AS (
    SELECT * 
    FROM {{ source('nba_project', 'line_score') }}
    )

SELECT 
	GAME_ID,
    CAST(GAME_DATE_EST AS TIMESTAMP) AS GAME_DATE_EST,
    GAME_SEQUENCE,
    TEAM_ID_HOME,
    CAST(TEAM_ABBREVIATION_HOME AS VARCHAR(255)) AS TEAM_ABBREVIATION_HOME,
    CAST(TEAM_CITY_NAME_HOME AS VARCHAR(255)) AS TEAM_CITY_NAME_HOME,
    CAST(TEAM_NICKNAME_HOME AS VARCHAR(255)) AS TEAM_NICKNAME_HOME,
    CAST(TEAM_WINS_LOSSES_HOME AS VARCHAR(255)) AS TEAM_WINS_LOSSES_HOME,
    PTS_QTR1_HOME,
    PTS_QTR2_HOME,
    PTS_QTR3_HOME,
    PTS_QTR4_HOME,
    PTS_OT1_HOME,
    PTS_OT2_HOME,
    PTS_OT3_HOME,
    PTS_OT4_HOME,
    CAST(PTS_OT5_HOME AS VARCHAR(255)) AS PTS_OT5_HOME,
    CAST(PTS_OT6_HOME AS VARCHAR(255)) AS PTS_OT6_HOME,
    CAST(PTS_OT7_HOME AS VARCHAR(255)) AS PTS_OT7_HOME,
    CAST(PTS_OT8_HOME AS VARCHAR(255)) AS PTS_OT8_HOME,
    CAST(PTS_OT9_HOME AS VARCHAR(255)) AS PTS_OT9_HOME,
    CAST(PTS_OT10_HOME AS VARCHAR(255)) AS PTS_OT10_HOME,
    PTS_HOME,
    TEAM_ID_AWAY,
    CAST(TEAM_ABBREVIATION_AWAY AS VARCHAR(255)) AS TEAM_ABBREVIATION_AWAY,
    CAST(TEAM_CITY_NAME_AWAY AS VARCHAR(255)) AS TEAM_CITY_NAME_AWAY,
    CAST(TEAM_NICKNAME_AWAY AS VARCHAR(255)) AS TEAM_NICKNAME_AWAY,
    CAST(TEAM_WINS_LOSSES_AWAY AS VARCHAR(255)) AS TEAM_WINS_LOSSES_AWAY,
    PTS_QTR1_AWAY,
    PTS_QTR2_AWAY,
    PTS_QTR3_AWAY,
    PTS_QTR4_AWAY,
    PTS_OT1_AWAY,
    PTS_OT2_AWAY,
    PTS_OT3_AWAY,
    PTS_OT4_AWAY,
    CAST(PTS_OT5_AWAY AS VARCHAR(255)) AS PTS_OT5_AWAY,
    CAST(PTS_OT6_AWAY AS VARCHAR(255)) AS PTS_OT6_AWAY,
    CAST(PTS_OT7_AWAY AS VARCHAR(255)) AS PTS_OT7_AWAY,
    CAST(PTS_OT8_AWAY AS VARCHAR(255)) AS PTS_OT8_AWAY,
    CAST(PTS_OT9_AWAY AS VARCHAR(255)) AS PTS_OT9_AWAY,
    CAST(PTS_OT10_AWAY AS VARCHAR(255)) AS PTS_OT10_AWAY,
    PTS_AWAY
FROM 
    src_scores