{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH SRC_PLAY_BY_PLAY AS (
    SELECT * 
    FROM {{ source('nba_project', 'play_by_play') }}
)

SELECT 
    GAME_ID,
    EVENTNUM,
    EVENTMSGTYPE,
    EVENTMSGACTIONTYPE,
    PERIOD,
    CAST(WCTIMESTRING AS VARCHAR(255)) AS WCTIMESTRING,
    CAST(PCTIMESTRING AS VARCHAR(255)) AS PCTIMESTRING,
    CAST(HOMEDESCRIPTION AS VARCHAR(255)) AS HOMEDESCRIPTION,
    CAST(NEUTRALDESCRIPTION AS VARCHAR(255)) AS NEUTRALDESCRIPTION,
    CAST(VISITORDESCRIPTION AS VARCHAR(255)) AS VISITORDESCRIPTION,
    CAST(SCORE AS VARCHAR(255)) AS SCORE,
    CAST(SCOREMARGIN AS VARCHAR(255)) AS SCOREMARGIN,
    PERSON1TYPE,
    CASE WHEN PLAYER1_ID = 0 THEN NULL ELSE PLAYER1_ID END AS PLAYER1_ID,
    CAST(PLAYER1_NAME AS VARCHAR(255)) AS PLAYER1_NAME,
    PLAYER1_TEAM_ID,
    CAST(PLAYER1_TEAM_CITY AS VARCHAR(255)) AS PLAYER1_TEAM_CITY,
    CAST(PLAYER1_TEAM_NICKNAME AS VARCHAR(255)) AS PLAYER1_TEAM_NICKNAME,
    CAST(PLAYER1_TEAM_ABBREVIATION AS VARCHAR(255)) AS PLAYER1_TEAM_ABBREVIATION,
    PERSON2TYPE,
    CASE WHEN PLAYER2_ID = 0 THEN NULL ELSE PLAYER2_ID END AS PLAYER2_ID,
    CAST(PLAYER2_NAME AS VARCHAR(255)) AS PLAYER2_NAME,
    PLAYER2_TEAM_ID,
    CAST(PLAYER2_TEAM_CITY AS VARCHAR(255)) AS PLAYER2_TEAM_CITY,
    CAST(PLAYER2_TEAM_NICKNAME AS VARCHAR(255)) AS PLAYER2_TEAM_NICKNAME,
    CAST(PLAYER2_TEAM_ABBREVIATION AS VARCHAR(255)) AS PLAYER2_TEAM_ABBREVIATION,
    PERSON3TYPE,
    CASE WHEN PLAYER3_ID = 0 THEN NULL ELSE PLAYER3_ID END AS PLAYER3_ID,
    CAST(PLAYER3_NAME AS VARCHAR(255)) AS PLAYER3_NAME,
    PLAYER3_TEAM_ID,
    CAST(PLAYER3_TEAM_CITY AS VARCHAR(255)) AS PLAYER3_TEAM_CITY,
    CAST(PLAYER3_TEAM_NICKNAME AS VARCHAR(255)) AS PLAYER3_TEAM_NICKNAME,
    CAST(PLAYER3_TEAM_ABBREVIATION AS VARCHAR(255)) AS PLAYER3_TEAM_ABBREVIATION,
    VIDEO_AVAILABLE_FLAG
FROM 
    SRC_PLAY_BY_PLAY
