{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_summary AS (
    SELECT * 
    FROM {{ source('nba_project', 'game_summary') }}
    )

SELECT 
	GAME_ID ,
	GAME_STATUS_ID ,
    GAME_DATE_EST ,
	GAME_SEQUENCE,
	CAST(GAME_STATUS_TEXT AS VARCHAR(255)) AS GAME_STATUS_TEXT,
	CAST(GAMECODE AS VARCHAR(255)) AS GAMECODE,
	HOME_TEAM_ID AS TEAM_ID_HOME,
	VISITOR_TEAM_ID AS TEAM_ID_AWAY,
	SEASON ,
	LIVE_PERIOD ,
	CAST(LIVE_PC_TIME AS VARCHAR(255)) AS LIVE_PC_TIME,
	CAST(NATL_TV_BROADCASTER_ABBREVIATION AS VARCHAR(255)) AS NATL_TV_BROADCASTER_ABBREVIATION,
	CAST(LIVE_PERIOD_TIME_BCAST AS VARCHAR(255)) AS LIVE_PERIOD_TIME_BCAST,
	WH_STATUS 
FROM 
    src_summary