{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_scores AS (
    SELECT * 
    FROM {{ source('nba_project', 'line_score') }}
)
SELECT 
    GAME_ID,
    CAST(GAME_DATE_EST AS TIMESTAMP) AS GAME_DATE_EST,
    GAME_SEQUENCE,
    TEAM_ID_HOME,
    CAST(TEAM_ABBREVIATION_HOME AS VARCHAR(255)) AS EQUIPO_ABREV_LOC,
    CAST(TEAM_CITY_NAME_HOME AS VARCHAR(255)) AS CIUDAD_EQUIPO_LOC,
    CAST(TEAM_NICKNAME_HOME AS VARCHAR(255)) AS APODO_EQUIPO_LOC,
    CAST(TEAM_WINS_LOSSES_HOME AS VARCHAR(255)) AS RECORD_EQUIPO_LOC,
    PTS_QTR1_HOME AS PTS_T1_LOC,
    PTS_QTR2_HOME AS PTS_T2_LOC,
    PTS_QTR3_HOME AS PTS_T3_LOC,
    PTS_QTR4_HOME AS PTS_T4_LOC,
    PTS_OT1_HOME AS PTS_OT1_LOC,
    PTS_OT2_HOME AS PTS_OT2_LOC,
    PTS_OT3_HOME AS PTS_OT3_LOC,
    PTS_OT4_HOME AS PTS_OT4_LOC,
    CAST(PTS_OT5_HOME AS VARCHAR(255)) AS PTS_OT5_LOC,
    CAST(PTS_OT6_HOME AS VARCHAR(255)) AS PTS_OT6_LOC,
    CAST(PTS_OT7_HOME AS VARCHAR(255)) AS PTS_OT7_LOC,
    CAST(PTS_OT8_HOME AS VARCHAR(255)) AS PTS_OT8_LOC,
    CAST(PTS_OT9_HOME AS VARCHAR(255)) AS PTS_OT9_LOC,
    CAST(PTS_OT10_HOME AS VARCHAR(255)) AS PTS_OT10_LOC,
    PTS_HOME AS PTS_LOC,
    TEAM_ID_AWAY,
    CAST(TEAM_ABBREVIATION_AWAY AS VARCHAR(255)) AS EQUIPO_ABREV_VIS,
    CAST(TEAM_CITY_NAME_AWAY AS VARCHAR(255)) AS CIUDAD_EQUIPO_VIS,
    CAST(TEAM_NICKNAME_AWAY AS VARCHAR(255)) AS APODO_EQUIPO_VIS,
    CAST(TEAM_WINS_LOSSES_AWAY AS VARCHAR(255)) AS RECORD_EQUIPO_VIS,
    PTS_QTR1_AWAY AS PTS_T1_VIS,
    PTS_QTR2_AWAY AS PTS_T2_VIS,
    PTS_QTR3_AWAY AS PTS_T3_VIS,
    PTS_QTR4_AWAY AS PTS_T4_VIS,
    PTS_OT1_AWAY AS PTS_OT1_VIS,
    PTS_OT2_AWAY AS PTS_OT2_VIS,
    PTS_OT3_AWAY AS PTS_OT3_VIS,
    PTS_OT4_AWAY AS PTS_OT4_VIS,
    CAST(PTS_OT5_AWAY AS VARCHAR(255)) AS PTS_OT5_VIS,
    CAST(PTS_OT6_AWAY AS VARCHAR(255)) AS PTS_OT6_VIS,
    CAST(PTS_OT7_AWAY AS VARCHAR(255)) AS PTS_OT7_VIS,
    CAST(PTS_OT8_AWAY AS VARCHAR(255)) AS PTS_OT8_VIS,
    CAST(PTS_OT9_AWAY AS VARCHAR(255)) AS PTS_OT9_VIS,
    CAST(PTS_OT10_AWAY AS VARCHAR(255)) AS PTS_OT10_VIS,
    PTS_AWAY AS PTS_VIS
FROM 
    src_scores