{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_draft_stats AS (
    SELECT * 
    FROM {{ source('nba_project', 'draft_combine_stats') }}
    )

SELECT 
    SEASON,
    PLAYER_ID,
    CAST(FIRST_NAME AS VARCHAR(255)) AS FIRST_NAME,
    CAST(LAST_NAME AS VARCHAR(255)) AS LAST_NAME,
    CAST(PLAYER_NAME AS VARCHAR(255)) AS PLAYER_NAME,
    CAST(POSITION AS VARCHAR(255)) AS POSICION,
    HEIGHT_WO_SHOES,
    CAST(HEIGHT_WO_SHOES_FT_IN AS VARCHAR(255)) AS HEIGHT_WO_SHOES_FT_IN,
    HEIGHT_W_SHOES,
    CAST(HEIGHT_W_SHOES_FT_IN AS VARCHAR(255)) AS HEIGHT_W_SHOES_FT_IN,
    WEIGHT,
    WINGSPAN,
    CAST(WINGSPAN_FT_IN AS VARCHAR(255)) AS WINGSPAN_FT_IN,
    STANDING_REACH,
    CAST(STANDING_REACH_FT_IN AS VARCHAR(255)) AS STANDING_REACH_FT_IN,
    BODY_FAT_PCT,
    HAND_LENGTH,
    HAND_WIDTH,
    STANDING_VERTICAL_LEAP,
    MAX_VERTICAL_LEAP,
    LANE_AGILITY_TIME,
    MODIFIED_LANE_AGILITY_TIME,
    THREE_QUARTER_SPRINT,
    BENCH_PRESS AS PRESS_BANCA,
    CAST(SPOT_FIFTEEN_CORNER_LEFT AS VARCHAR(255)) AS SPOT_FIFTEEN_CORNER_LEFT,
    CAST(SPOT_FIFTEEN_BREAK_LEFT AS VARCHAR(255)) AS SPOT_FIFTEEN_BREAK_LEFT,
    CAST(SPOT_FIFTEEN_TOP_KEY AS VARCHAR(255)) AS SPOT_FIFTEEN_TOP_KEY,
    CAST(SPOT_FIFTEEN_BREAK_RIGHT AS VARCHAR(255)) AS SPOT_FIFTEEN_BREAK_RIGHT,
    CAST(SPOT_FIFTEEN_CORNER_RIGHT AS VARCHAR(255)) AS SPOT_FIFTEEN_CORNER_RIGHT,
    CAST(SPOT_COLLEGE_CORNER_LEFT AS VARCHAR(255)) AS SPOT_COLLEGE_CORNER_LEFT,
    CAST(SPOT_COLLEGE_BREAK_LEFT AS VARCHAR(255)) AS SPOT_COLLEGE_BREAK_LEFT,
    CAST(SPOT_COLLEGE_TOP_KEY AS VARCHAR(255)) AS SPOT_COLLEGE_TOP_KEY,
    CAST(SPOT_COLLEGE_BREAK_RIGHT AS VARCHAR(255)) AS SPOT_COLLEGE_BREAK_RIGHT,
    CAST(SPOT_COLLEGE_CORNER_RIGHT AS VARCHAR(255)) AS SPOT_COLLEGE_CORNER_RIGHT,
    CAST(SPOT_NBA_CORNER_LEFT AS VARCHAR(255)) AS SPOT_NBA_CORNER_LEFT,
    CAST(SPOT_NBA_BREAK_LEFT AS VARCHAR(255)) AS SPOT_NBA_BREAK_LEFT,
    CAST(SPOT_NBA_TOP_KEY AS VARCHAR(255)) AS SPOT_NBA_TOP_KEY,
    CAST(SPOT_NBA_BREAK_RIGHT AS VARCHAR(255)) AS SPOT_NBA_BREAK_RIGHT,
    CAST(SPOT_NBA_CORNER_RIGHT AS VARCHAR(255)) AS SPOT_NBA_CORNER_RIGHT,
    CAST(OFF_DRIB_FIFTEEN_BREAK_LEFT AS VARCHAR(255)) AS OFF_DRIB_FIFTEEN_BREAK_LEFT,
    CAST(OFF_DRIB_FIFTEEN_TOP_KEY AS VARCHAR(255)) AS OFF_DRIB_FIFTEEN_TOP_KEY,
    CAST(OFF_DRIB_FIFTEEN_BREAK_RIGHT AS VARCHAR(255)) AS OFF_DRIB_FIFTEEN_BREAK_RIGHT,
    CAST(OFF_DRIB_COLLEGE_BREAK_LEFT AS VARCHAR(255)) AS OFF_DRIB_COLLEGE_BREAK_LEFT,
    CAST(OFF_DRIB_COLLEGE_TOP_KEY AS VARCHAR(255)) AS OFF_DRIB_COLLEGE_TOP_KEY,
    CAST(OFF_DRIB_COLLEGE_BREAK_RIGHT AS VARCHAR(255)) AS OFF_DRIB_COLLEGE_BREAK_RIGHT,
    CAST(ON_MOVE_FIFTEEN AS VARCHAR(255)) AS ON_MOVE_FIFTEEN,
    CAST(ON_MOVE_COLLEGE AS VARCHAR(255)) AS ON_MOVE_COLLEGE
FROM 
    src_draft_stats