{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_players AS (
    SELECT * 
    FROM {{ source('nba_project', 'common_player_info') }}
    ),

renamed_casted AS (
    SELECT 
    PERSON_ID AS PLAYER_ID,
    CAST(HEIGHT AS VARCHAR(255)) AS HEIGHT,
    ROUND(
        CAST(SPLIT_PART(HEIGHT, '-', 1) AS FLOAT) + 
        (CAST(SPLIT_PART(HEIGHT, '-', 2) AS FLOAT) / 12) 
        ,2
    ) AS HEIGHT_IN_FEET,
    ROUND((HEIGHT_IN_FEET * 0.304), 2) AS HEIGHT_IN_METERS,
    CAST(WEIGHT AS DECIMAL(10, 2)) AS WEIGHT,
    CAST(DISPLAY_FIRST_LAST AS VARCHAR(255)) AS DISPLAY_FIRST_LAST,
    CAST(PLAYER_SLUG AS VARCHAR(255)) AS PLAYER_SLUG,
    {{ dbt_date.convert_timezone('BIRTHDATE', 'GMT', 'UTC') }} AS BIRTHDATE_UTC,
    CAST(SCHOOL AS VARCHAR(255)) AS SCHOOL,
    CAST(COUNTRY AS VARCHAR(255)) AS COUNTRY,
    CAST(LAST_AFFILIATION AS VARCHAR(255)) AS LAST_AFFILIATION,
    CAST(SEASON_EXP AS DECIMAL(10, 0)) AS SEASON_EXP,
    CAST(JERSEY AS VARCHAR(255)) AS JERSEY,
    CAST(POSITION AS VARCHAR(255)) AS POSITION,
    CAST(ROSTERSTATUS AS VARCHAR(255)) AS ROSTERSTATUS,
    TEAM_ID,
    CAST(TEAM_CODE AS VARCHAR(255)) AS TEAM_CODE,
    CAST(TEAM_NAME AS VARCHAR(255)) AS TEAM_NAME,
    CAST(TEAM_ABBREVIATION AS VARCHAR(255)) AS TEAM_ABBREVIATION,
    CAST(TEAM_CITY AS VARCHAR(255)) AS TEAM_CITY,
    CAST(PLAYERCODE AS VARCHAR(255)) AS PLAYERCODE,
    CAST(DISPLAY_LAST_COMMA_FIRST AS VARCHAR(255)) AS DISPLAY_LAST_COMMA_FIRST,
    CAST(DISPLAY_FI_LAST AS VARCHAR(255)) AS DISPLAY_FI_LAST,
    CAST(FROM_YEAR AS INTEGER) AS FROM_YEAR,
    CAST(TO_YEAR AS INTEGER) AS TO_YEAR,
    CAST(DRAFT_YEAR AS VARCHAR(255)) AS DRAFT_YEAR,
    CAST(DRAFT_ROUND AS VARCHAR(255)) AS DRAFT_ROUND,
    CAST(DRAFT_NUMBER AS VARCHAR(255)) AS DRAFT_NUMBER,
    CAST(GAMES_PLAYED_CURRENT_SEASON_FLAG AS BOOLEAN) AS GAMES_PLAYED_CURRENT_SEASON_FLAG,
    CAST(DLEAGUE_FLAG AS BOOLEAN) AS DLEAGUE_FLAG,
    CAST(NBA_FLAG AS BOOLEAN) AS NBA_FLAG,
    CAST(GAMES_PLAYED_FLAG AS BOOLEAN) AS GAMES_PLAYED_FLAG,
    CAST(GREATEST_75_FLAG AS BOOLEAN) AS GREATEST_75_FLAG
    FROM src_players
    )

SELECT * FROM renamed_casted