{{
  config(
    materialized='view',
    schema="base"
  )
}}

WITH src_games AS (
    SELECT * 
    FROM {{ source('nba_project', 'game') }}
    ),


deduplicated_games AS (
    SELECT 
        *,
        ROW_NUMBER() OVER (PARTITION BY GAME_ID ORDER BY GAME_DATE DESC) AS row_num
    FROM 
        src_games
)
SELECT 
    GAME_ID,
    SEASON_ID,
    SEASON_TYPE,
    GAME_DATE,

    TEAM_ID_HOME,
    CAST(TEAM_ABBREVIATION_HOME AS VARCHAR(255)) AS EQUIPO_ABREV_LOC,
    CAST(TEAM_NAME_HOME AS VARCHAR(255)) AS EQUIPO_NOM_LOC,
    CAST(MATCHUP_HOME AS VARCHAR(255)) AS ENFRENT_LOC,
    CAST(WL_HOME AS VARCHAR(255)) AS RESULT_LOC,
    MIN AS MINUTOS_LOC,
    FGM_HOME AS TC_ENC_LOC,
    FGA_HOME AS TC_INT_LOC,
    FG_PCT_HOME AS TC_PCT_LOC,
    FG3M_HOME AS T3_ENC_LOC,
    FG3A_HOME AS T3_INT_LOC,
    CAST(FG3_PCT_HOME AS VARCHAR(255)) AS T3_PCT_PORC_LOC,
    FTM_HOME AS TL_ENC_LOC,
    FTA_HOME AS TL_INT_LOC,
    FT_PCT_HOME AS TL_PCT_LOC,
    CAST(OREB_HOME AS VARCHAR(255)) AS REB_OF_LOC,
    CAST(DREB_HOME AS VARCHAR(255)) AS REB_DEF_LOC,
    REB_HOME AS REB_TOT_LOC,
    AST_HOME AS ASIST_LOC,
    CAST(STL_HOME AS VARCHAR(255)) AS ROBOS_LOC,
    CAST(BLK_HOME AS VARCHAR(255)) AS TAPONES_LOC,
    CAST(TOV_HOME AS VARCHAR(255)) AS PERDIDAS_LOC,
    PF_HOME AS FALTAS_LOC,
    PTS_HOME AS PTS_LOC,
    PLUS_MINUS_HOME AS PM_LOC,
    CAST(VIDEO_AVAILABLE_HOME AS BOOLEAN) AS VIDEO_AVAILABLE_HOME,

    TEAM_ID_AWAY,
    CAST(TEAM_ABBREVIATION_AWAY AS VARCHAR(255)) AS EQUIPO_ABREV_VIS,
    CAST(TEAM_NAME_AWAY AS VARCHAR(255)) AS EQUIPO_NOM_VIS,
    CAST(MATCHUP_AWAY AS VARCHAR(255)) AS ENFRENT_VIS,
    CAST(WL_AWAY AS VARCHAR(255)) AS RESULT_VIS,
    FGM_AWAY AS TC_ENC_VIS,
    FGA_AWAY AS TC_INT_VIS,
    FG_PCT_AWAY AS TC_PCT_VIS,
    FG3M_AWAY AS T3_ENC_VIS,
    FG3A_AWAY AS T3_INT_VIS,
    CAST(FG3_PCT_AWAY AS VARCHAR(255)) AS T3_PCT_PORC_VIS,
    FTM_AWAY AS TL_ENC_VIS,
    FTA_AWAY AS TL_INT_VIS,
    FT_PCT_AWAY AS TL_PCT_VIS,
    CAST(OREB_AWAY AS VARCHAR(255)) AS REB_OF_VIS,
    CAST(DREB_AWAY AS VARCHAR(255)) AS REB_DEF_VIS,
    REB_AWAY AS REB_TOT_VIS,
    AST_AWAY AS ASIST_VIS,
    CAST(STL_AWAY AS VARCHAR(255)) AS ROBOS_VIS,
    CAST(BLK_AWAY AS VARCHAR(255)) AS TAPONES_VIS,
    CAST(TOV_AWAY AS VARCHAR(255)) AS PERDIDAS_VIS,
    PF_AWAY AS FALTAS_VIS,
    PTS_AWAY AS PTS_VIS,
    PLUS_MINUS_AWAY AS PM_VIS,
    CAST(VIDEO_AVAILABLE_AWAY AS BOOLEAN) AS VIDEO_AVAILABLE_AWAY
FROM 
    deduplicated_games
WHERE row_num = 1
